version: '3.7'
services:
  app:
    build: .
    environment:
      - PORT=8080
      - JWT_SECRET=secret
      - DB_URL=mongodb://admin:admin@localhost:27017
    ports:
      - "8080:8080"
    links:
      - mongodb
    networks:
      - internal
      
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: nodeBoilerplate
    networks:
      - internal

networks:
  internal:
    driver: bridge